import { EmotionCardDto } from "../types";

export const emotions: EmotionCardDto[] = [
    {
        id: 1,
        name: "Радість",
        description: "Стан внутрішнього підйому, задоволення та позитиву.",
        emoji: "😊",
        color: "#FFD93B",
    },
    {
        id: 2,
        name: "Сум",
        description: "Стан пригніченості, меланхолії або втрати.",
        emoji: "😢",
        color: "#92A8D1",
    },
    {
        id: 3,
        name: "Гнів",
        description: "Сильне почуття роздратування або злості.",
        emoji: "😡",
        color: "#D9534F",
    },
    {
        id: 4,
        name: "Страх",
        description: "Емоція, викликана відчуттям загрози чи небезпеки.",
        emoji: "😨",
        color: "#D2B4DE",
    },
    {
        id: 5,
        name: "Здивування",
        description: "Реакція на несподівану або незвичну подію.",
        emoji: "😲",
        color: "#F7DC6F",
    },
    {
        id: 6,
        name: "Огида",
        description: "Негативна реакція на щось огидне або неприйнятне.",
        emoji: "🤢",
        color: "#7DCEA0",
    },
    {
        id: 7,
        name: "Спокій",
        description: "Внутрішній баланс, відсутність тривоги або збудження.",
        emoji: "😌",
        color: "#AED6F1",
    },
    {
        id: 8,
        name: "Захоплення",
        description: "Почуття великого інтересу або радості від чогось.",
        emoji: "🤩",
        color: "#F4D03F",
    },
];





export const EMOTIONS_VARIANTS = [
    { id: 1, name: "Радість", emoji: "😊", color: "#FFD93B" },
    { id: 2, name: "Смуток", emoji: "😢", color: "#92A8D1" },
    { id: 3, name: "Злість", emoji: "😡", color: "#D9534F" },
    { id: 4, name: "Подив", emoji: "😲", color: "#F7DC6F" },
    { id: 5, name: "Спокій", emoji: "😌", color: "#AED6F1" },
    { id: 6, name: "Огида", emoji: "🤢", color: "#7DCEA0" },
    { id: 7, name: "Страх", emoji: "😨", color: "#D2B4DE" },
    { id: 8, name: "Захоплення", emoji: "🤩", color: "#F4D03F" },
    { id: 9, name: "Нудьга", emoji: "🥱", color: "#D5D8DC" },
    { id: 10, name: "Сором", emoji: "😳", color: "#F5B7B1" },
    { id: 11, name: "Незручність", emoji: "😬", color: "#E59866" },
    { id: 12, name: "Впевненість", emoji: "😎", color: "#45B39D" },
    { id: 13, name: "Тривога", emoji: "😟", color: "#AEB6BF" },
    { id: 14, name: "Зніяковілість", emoji: "🙈", color: "#FAD7A0" },
    { id: 15, name: "Любов", emoji: "😍", color: "#F1948A" },
    { id: 16, name: "Ненависть", emoji: "😠", color: "#C0392B" },
    { id: 17, name: "Очікування", emoji: "⏳", color: "#7FB3D5" },
    { id: 18, name: "Вина", emoji: "😔", color: "#85929E" },
    { id: 19, name: "Розгубленість", emoji: "🤔", color: "#F0B27A" },
    { id: 20, name: "Гордiсть", emoji: "😤", color: "#CD6155" },
    { id: 21, name: "Сарказм", emoji: "😏", color: "#7D3C98" },
    { id: 22, name: "Бажання", emoji: "🥵", color: "#E74C3C" },
    { id: 23, name: "Сонливість", emoji: "😴", color: "#A9CCE3" },
    { id: 24, name: "Несподіванка", emoji: "😯", color: "#F9E79F" },
    { id: 25, name: "Легкість", emoji: "😇", color: "#ABEBC6" },
    { id: 26, name: "Нервозність", emoji: "😬", color: "#E59866" },
    { id: 27, name: "Жалість", emoji: "😞", color: "#95A5A6" },
    { id: 28, name: "Надія", emoji: "🙏", color: "#F8C471" },
    { id: 29, name: "Заздрість", emoji: "😒", color: "#B2BABB" },
    { id: 30, name: "Розчарування", emoji: "😞", color: "#95A5A6" },
    { id: 31, name: "Веселощі", emoji: "😂", color: "#FADBD8" },
    { id: 32, name: "Задумливість", emoji: "🧐", color: "#BB8FCE" },
    { id: 33, name: "Подяка", emoji: "🤗", color: "#F5CBA7" },
    { id: 34, name: "Напруження", emoji: "😣", color: "#D98880" },
    { id: 35, name: "Рішучість", emoji: "😤", color: "#CD6155" },
    { id: 36, name: "Хвилювання", emoji: "😰", color: "#5DADE2" },
    { id: 37, name: "Енергія", emoji: "⚡", color: "#F1C40F" },
    { id: 38, name: "Мрійливість", emoji: "💭", color: "#D7DBDD" },
    { id: 39, name: "Щастя", emoji: "😁", color: "#F7DC6F" },
    { id: 40, name: "Надихання", emoji: "🌟", color: "#F9E79F" },
    { id: 41, name: "Збудження", emoji: "😜", color: "#F8C471" },
    { id: 42, name: "Теплота", emoji: "🔥", color: "#E74C3C" },
    { id: 43, name: "Сумнів", emoji: "😕", color: "#AAB7B8" },
    { id: 44, name: "Паніка", emoji: "😱", color: "#A569BD" },
    { id: 45, name: "Інтерес", emoji: "🧠", color: "#F1948A" },
    { id: 46, name: "Схвалення", emoji: "👍", color: "#58D68D" },
    { id: 47, name: "Насолода", emoji: "😋", color: "#FAD7A0" },
    { id: 48, name: "Безсилля", emoji: "😩", color: "#85929E" },
    { id: 49, name: "Сюрприз", emoji: "🎉", color: "#F5B041" },
    { id: 50, name: "Турбота", emoji: "🤲", color: "#EDBB99" },
    { id: 51, name: "Ненависть до себе", emoji: "😖", color: "#AF7AC5" },
    { id: 52, name: "Втеча", emoji: "🏃‍♂️", color: "#7FB3D5" },
    { id: 53, name: "Невпевненість", emoji: "😓", color: "#AED6F1" },
    { id: 54, name: "Співчуття", emoji: "💔", color: "#E74C3C" },
    { id: 55, name: "Безпека", emoji: "🛡️", color: "#5D6D7E" },
    { id: 56, name: "Приязнь", emoji: "🫶", color: "#FADBD8" },
    { id: 57, name: "Захист", emoji: "🤝", color: "#85C1E9" },
    { id: 58, name: "Сором'язливість", emoji: "😶", color: "#D5D8DC" },
    { id: 59, name: "Байдужість", emoji: "😐", color: "#BFC9CA" },
    { id: 60, name: "Збентеження", emoji: "😅", color: "#F9E79F" },
    { id: 61, name: "Жах", emoji: "👻", color: "#D7DBDD" },
    { id: 62, name: "Мотивація", emoji: "🚀", color: "#A2D9CE" },
    { id: 63, name: "Роздратування", emoji: "😤", color: "#CD6155" },
    { id: 64, name: "Неприязнь", emoji: "😖", color: "#AF7AC5" },
    { id: 65, name: "Іронія", emoji: "😏", color: "#7D3C98" },
    { id: 66, name: "Комфорт", emoji: "🛋️", color: "#D5DBDB" },
    { id: 67, name: "Захопленість", emoji: "🤯", color: "#FAD7A0" },
    { id: 68, name: "Печаль", emoji: "😭", color: "#ABB2B9" },
    { id: 69, name: "Натхнення", emoji: "🌈", color: "#A3E4D7" },
    { id: 70, name: "Ейфорія", emoji: "🥳", color: "#F7DC6F" },
    { id: 71, name: "Скромність", emoji: "🙇‍♂️", color: "#D2B4DE" },
    { id: 72, name: "Здивування", emoji: "😮", color: "#F8C471" },
    { id: 73, name: "Незадоволення", emoji: "😠", color: "#C0392B" },
    { id: 74, name: "Милосердя", emoji: "💞", color: "#F1948A" },
    { id: 75, name: "Задоволення", emoji: "😌", color: "#AED6F1" },
    { id: 76, name: "Відчай", emoji: "😫", color: "#A9CCE3" },
    { id: 77, name: "Повага", emoji: "🎩", color: "#566573" },
    { id: 78, name: "Примирення", emoji: "🤝", color: "#85C1E9" },
    { id: 79, name: "Підтримка", emoji: "🫂", color: "#FADBD8" },
    { id: 80, name: "Відраза", emoji: "🤮", color: "#52BE80" },
    { id: 81, name: "Жвавість", emoji: "🕺", color: "#F9E79F" },
    { id: 82, name: "Теплота душі", emoji: "❤️", color: "#E74C3C" },
    { id: 83, name: "Зневага", emoji: "😒", color: "#B2BABB" },
    { id: 84, name: "Образа", emoji: "😤", color: "#CD6155" },
    { id: 85, name: "Симпатія", emoji: "😊", color: "#FFD93B" },
    { id: 86, name: "Довіра", emoji: "🤝", color: "#85C1E9" },
    { id: 87, name: "Надмірність", emoji: "😵", color: "#D5D8DC" },
    { id: 88, name: "Пригнічення", emoji: "😞", color: "#95A5A6" },
    { id: 89, name: "Жартівливість", emoji: "😜", color: "#F8C471" },
    { id: 90, name: "Емпатія", emoji: "🫶", color: "#FADBD8" },
    { id: 91, name: "Цікавість", emoji: "🔍", color: "#AED6F1" },
    { id: 92, name: "Відкритість", emoji: "👐", color: "#D6EAF8" },
    { id: 93, name: "Тривожність", emoji: "😰", color: "#5DADE2" },
    { id: 94, name: "Обожнювання", emoji: "🥰", color: "#F5B7B1" },
    { id: 95, name: "Покора", emoji: "🙇", color: "#BB8FCE" },
    { id: 96, name: "Шок", emoji: "🤯", color: "#FAD7A0" },
    { id: 97, name: "Піднесення", emoji: "🎈", color: "#F5B041" },
    { id: 98, name: "Терпимість", emoji: "🧘", color: "#D0ECE7" },
    { id: 99, name: "Загубленість", emoji: "🗺️", color: "#B2BABB" },
    { id: 100, name: "Мудрість", emoji: "🦉", color: "#A569BD" }
];
