import { EmotionCardDto } from "../types";

export const emotions: EmotionCardDto[] = [
    {
        id: 1,
        name: "Радість",
        description: "Стан внутрішнього підйому, задоволення та позитиву.",
        emoji: "😊",
    },
    {
        id: 2,
        name: "Сум",
        description: "Стан пригніченості, меланхолії або втрати.",
        emoji: "😢",
    },
    {
        id: 3,
        name: "Гнів",
        description: "Сильне почуття роздратування або злості.",
        emoji: "😡",
    },
    {
        id: 4,
        name: "Страх",
        description: "Емоція, викликана відчуттям загрози чи небезпеки.",
        emoji: "😨",
    },
    {
        id: 5,
        name: "Здивування",
        description: "Реакція на несподівану або незвичну подію.",
        emoji: "😲",
    },
    {
        id: 6,
        name: "Огида",
        description: "Негативна реакція на щось огидне або неприйнятне.",
        emoji: "🤢",
    },
    {
        id: 7,
        name: "Спокій",
        description: "Внутрішній баланс, відсутність тривоги або збудження.",
        emoji: "😌",
    },
    {
        id: 8,
        name: "Захоплення",
        description: "Почуття великого інтересу або радості від чогось.",
        emoji: "🤩",
    },
];





export const EMOTIONS_VARIANTS = [
    { id: 1, name: "Радість", emoji: "😊" },
    { id: 2, name: "Смуток", emoji: "😢" },
    { id: 3, name: "Злість", emoji: "😡" },
    { id: 4, name: "Подив", emoji: "😲" },
    { id: 5, name: "Спокій", emoji: "😌" },
    { id: 6, name: "Огида", emoji: "🤢" },
    { id: 7, name: "Страх", emoji: "😨" },
    { id: 8, name: "Захоплення", emoji: "🤩" },
    { id: 9, name: "Нудьга", emoji: "🥱" },
    { id: 10, name: "Сором", emoji: "😳" },
    { id: 11, name: "Незручність", emoji: "😬" },
    { id: 12, name: "Впевненість", emoji: "😎" },
    { id: 13, name: "Тривога", emoji: "😟" },
    { id: 14, name: "Зніяковілість", emoji: "🙈" },
    { id: 15, name: "Любов", emoji: "😍" },
    { id: 16, name: "Ненависть", emoji: "😠" },
    { id: 17, name: "Очікування", emoji: "⏳" },
    { id: 18, name: "Вина", emoji: "😔" },
    { id: 19, name: "Розгубленість", emoji: "🤔" },
    { id: 20, name: "Гордiсть", emoji: "😤" },
    { id: 21, name: "Сарказм", emoji: "😏" },
    { id: 22, name: "Бажання", emoji: "🥵" },
    { id: 23, name: "Сонливість", emoji: "😴" },
    { id: 24, name: "Несподіванка", emoji: "😯" },
    { id: 25, name: "Легкість", emoji: "😇" },
    { id: 26, name: "Нервозність", emoji: "😬" },
    { id: 27, name: "Жалість", emoji: "😞" },
    { id: 28, name: "Надія", emoji: "🙏" },
    { id: 29, name: "Заздрість", emoji: "😒" },
    { id: 30, name: "Розчарування", emoji: "😞" },
    { id: 31, name: "Веселощі", emoji: "😂" },
    { id: 32, name: "Задумливість", emoji: "🧐" },
    { id: 33, name: "Подяка", emoji: "🤗" },
    { id: 34, name: "Напруження", emoji: "😣" },
    { id: 35, name: "Рішучість", emoji: "😤" },
    { id: 36, name: "Хвилювання", emoji: "😰" },
    { id: 37, name: "Енергія", emoji: "⚡" },
    { id: 38, name: "Мрійливість", emoji: "💭" },
    { id: 39, name: "Щастя", emoji: "😁" },
    { id: 40, name: "Надихання", emoji: "🌟" },
    { id: 41, name: "Збудження", emoji: "😜" },
    { id: 42, name: "Теплота", emoji: "🔥" },
    { id: 43, name: "Сумнів", emoji: "😕" },
    { id: 44, name: "Паніка", emoji: "😱" },
    { id: 45, name: "Інтерес", emoji: "🧠" },
    { id: 46, name: "Схвалення", emoji: "👍" },
    { id: 47, name: "Насолода", emoji: "😋" },
    { id: 48, name: "Безсилля", emoji: "😩" },
    { id: 49, name: "Сюрприз", emoji: "🎉" },
    { id: 50, name: "Турбота", emoji: "🤲" },
    { id: 51, name: "Ненависть до себе", emoji: "😖" },
    { id: 52, name: "Втеча", emoji: "🏃‍♂️" },
    { id: 53, name: "Невпевненість", emoji: "😓" },
    { id: 54, name: "Співчуття", emoji: "💔" },
    { id: 55, name: "Безпека", emoji: "🛡️" },
    { id: 56, name: "Приязнь", emoji: "🫶" },
    { id: 57, name: "Захист", emoji: "🤝" },
    { id: 58, name: "Сором'язливість", emoji: "😶" },
    { id: 59, name: "Байдужість", emoji: "😐" },
    { id: 60, name: "Збентеження", emoji: "😅" },
    { id: 61, name: "Жах", emoji: "👻" },
    { id: 62, name: "Мотивація", emoji: "🚀" },
    { id: 63, name: "Роздратування", emoji: "😤" },
    { id: 64, name: "Неприязнь", emoji: "😖" },
    { id: 65, name: "Іронія", emoji: "😏" },
    { id: 66, name: "Комфорт", emoji: "🛋️" },
    { id: 67, name: "Захопленість", emoji: "🤯" },
    { id: 68, name: "Печаль", emoji: "😭" },
    { id: 69, name: "Натхнення", emoji: "🌈" },
    { id: 70, name: "Ейфорія", emoji: "🥳" },
    { id: 71, name: "Скромність", emoji: "🙇‍♂️" },
    { id: 72, name: "Здивування", emoji: "😮" },
    { id: 73, name: "Незадоволення", emoji: "😠" },
    { id: 74, name: "Милосердя", emoji: "💞" },
    { id: 75, name: "Задоволення", emoji: "😌" },
    { id: 76, name: "Відчай", emoji: "😫" },
    { id: 77, name: "Повага", emoji: "🎩" },
    { id: 78, name: "Примирення", emoji: "🤝" },
    { id: 79, name: "Підтримка", emoji: "🫂" },
    { id: 80, name: "Відраза", emoji: "🤮" },
    { id: 81, name: "Жвавість", emoji: "🕺" },
    { id: 82, name: "Теплота душі", emoji: "❤️" },
    { id: 83, name: "Зневага", emoji: "😒" },
    { id: 84, name: "Образа", emoji: "😤" },
    { id: 85, name: "Симпатія", emoji: "😊" },
    { id: 86, name: "Довіра", emoji: "🤝" },
    { id: 87, name: "Надмірність", emoji: "😵" },
    { id: 88, name: "Пригнічення", emoji: "😞" },
    { id: 89, name: "Жартівливість", emoji: "😜" },
    { id: 90, name: "Емпатія", emoji: "🫶" },
    { id: 91, name: "Цікавість", emoji: "🔍" },
    { id: 92, name: "Відкритість", emoji: "👐" },
    { id: 93, name: "Тривожність", emoji: "😰" },
    { id: 94, name: "Обожнювання", emoji: "🥰" },
    { id: 95, name: "Покора", emoji: "🙇" },
    { id: 96, name: "Шок", emoji: "🤯" },
    { id: 97, name: "Піднесення", emoji: "🎈" },
    { id: 98, name: "Терпимість", emoji: "🧘" },
    { id: 99, name: "Загубленість", emoji: "🗺️" },
    { id: 100, name: "Мудрість", emoji: "🦉" }
];
